import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import { QueryClientProviderWrapper } from '@/app/providers/QueryProvider';
import './globals.css';
import { Toaster } from 'sonner';

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'CoinTrack',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProviderWrapper>
        <body className={`${rubik.variable} antialiased`} cz-shortcut-listen="true">
          {children}
          <Toaster position="top-right" richColors closeButton theme="dark" />
        </body>
      </QueryClientProviderWrapper>
    </html>
  );
}
